apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-specialist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-specialist-api
  template:
    metadata:
      labels:
        app: bot-specialist-api
    spec:
      imagePullSecrets:
      - name: gcp-artifact-registry
      containers:
      - name: bot-specialist-api
        image: us-central1-docker.pkg.dev/the-bot-specialist-dev/bot-especialist-repo/us-central1-docker.pkg.dev/the-bot-specialist-dev/bot-specialist-repov1/bot-especialist:v1
        ports:
          - containerPort: 8090
        env:
          - name: PORT
            value: "8090"
