---
name: Running Project Unit Tests
description: Runs all project unit tests
on:
  pull_request:
    branches:
      - dev
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        echo "Running all Unit tests..."
        echo
        python -m unittest discover -s tests -p "test_*.py" -v
        echo
        echo "All unit test were run."

      shell: bash
