---
name: Running Project Unit Tests
description: Runs all project unit tests
on:
  pull_request:
    branches:
      - dev
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest
        echo "dependencies for unit tests were installed"


    - name: Run tests
      run: |
        echo "Running all Unit tests..."
        echo
        python -m unittest discover -s <test_directory> -p "test_*.py" -v
        echo
        echo "All unit test were run."
