---
name: Poetry Install
description: Poetry install dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ github.run_id }}

    - name: Install dependencies
      run: |
        alias python=/usr/bin/python3.9
        curl -sSL https://install.python-poetry.org | python -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        poetry --version
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.create true
        poetry config installer.parallel true
        poetry config cache-dir $(HOME)/.cache/pypoetry
        poetry install --no-interaction --no-ansi
      shell: bash
