name: Composer Sync & Docker Build DEV

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  ENVIRONMENT: "dev"
  PROJECT_ID: "the-bot-specialist-dev"
  BEAM_VERSION: "2.59.0"
  BEAM_IMAGE: "apache/beam_python3.11_sdk"
  VERSION_FILE: 'src/bot_especialist/__init__.py'
  PYTHON_IMAGE: "python:3.9"
  CONTAINER_IMAGE: "us-central1-docker.pkg.dev/the-bot-specialist-dev/bot-specialist-repov1/bot-specialist-dev:v1"
  REGISTRY_REPO_NAME: "bot-especialist-repo"
  REGION: "us-central1"
  GKE_DISK_SIZE: "25"
  GKE_MIN_NODES: "1"
  GKE_MAX_NODES: "1"
  GKE_MACHINE_TYPE: "e2-medium"


jobs:
  composer-sync:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set Package Version
        id: set_version
        uses: ./.github/actions/set-version
        with:
          FILE_PATH: ${{ env.VERSION_FILE }}

      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Workflow Variables
        uses: ./.github/actions/set-env-vars
        with:
          VERSION: ${{ steps.set_version.outputs.VERSION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}

  docker-build:
    needs: composer-sync
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set Package Version
        id: set_version
        uses: ./.github/actions/set-version
        with:
          FILE_PATH: ${{ env.VERSION_FILE }}

      - name: Install dependencies
        id: poetry_install
        uses: ./.github/actions/poetry-install

      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Workflow Variables
        uses: ./.github/actions/set-env-vars
        with:
          VERSION: ${{ steps.set_version.outputs.VERSION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}

      - name: Check App functions with unit tests
        id: check_functionalities
        uses: ./.github/actions/run-unit-tests

      - name: Provision, Build & Push
        uses: ./.github/actions/provision-build-push
        with:
          PYTHON_IMAGE: ${{ env.PYTHON_IMAGE }}
          REGISTRY_REPO_NAME: ${{ env.REGISTRY_REPO_NAME }}
          CONTAINER_IMAGE: ${{ env.CONTAINER_IMAGE }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          REGION: ${{ env.REGION }}
          GKE_DISK_SIZE: ${{ env.GKE_DISK_SIZE }}
          GKE_MAX_NODES: ${{ env.GKE_MAX_NODES }}
          GKE_MACHINE_TYPE: ${{ env.GKE_MACHINE_TYPE }}
